export const REPOSITORIES = [
	{
		title: 'Bewear - Plataforma de Ecommerce',
		subtitle: 'Projeto FullStack',
		img: '/repositories/bewear.png',
		repo: 'https://github.com/code-front-braga/bewear-bootcamp-fullstack-club',
		deploy: 'https://bewear-bootcamp-fullstack-club-3n6y.vercel.app/',
		tags: ['nextjs', 'typescript', 'tailwindcss', 'drizzle', 'better-auth', 'tanstack/query', 'stripe'],
	},
	{
		title: 'AYSE - Sistema de Gerenciamento de Compras em Supermercados',
		subtitle: 'Projeto FullStack',
		img: '/repositories/ayse.png',
		repo: 'https://github.com/code-front-braga/ayse-mvp-project',
		deploy: 'https://ayse-mvp-project.vercel.app/',
		tags: ['nextjs', 'typescript', 'tailwindcss', 'prisma orm', 'better-auth', 'postgresql', 'jspdf'],
	},
	{
		title: 'Template de Autenticação',
		subtitle: '',
		img: '/repositories/auth.png',
		repo: 'https://github.com/code-front-braga/auth-template',
		deploy: 'https://auth-template-zeta.vercel.app/auth',
		tags: ['nextjs', 'typescript', 'tailwindcss', 'prisma orm', 'next-auth', 'postgresql'],
	},
	{
		title: 'FSW Donalds - Terminal de Autoatendimento do Mac Donalds',
		subtitle: 'Projeto FullStack',
		img: '/repositories/mac.png',
		repo: 'https://github.com/code-front-braga/fsc-self-checkout',
		deploy: 'https://fsc-self-checkout.vercel.app/',
		tags: ['nextjs', 'typescript', 'tailwindcss', 'prisma orm', 'authjs', 'sqlite', 'stripe'],
	},
	{
		title: 'Quiz Programação',
		subtitle: '',
		img: '/repositories/quiz.png',
		repo: 'https://github.com/code-front-braga/Quiz_Programming',
		deploy: 'https://pr-quiz-programming.vercel.app/',
		tags: ['typescript', 'html', 'css', 'sass'],
	},
	{
		title: 'Guia de Alimentação - Landing Page',
		subtitle: '',
		img: '/repositories/imc.png',
		repo: 'https://github.com/code-front-braga/Body_Mass_Index',
		deploy: 'https://pr-body-mass-index.vercel.app/',
		tags: ['typescript', 'html', 'css'],
	},
	{
		title: 'Rei Leão - Landing Page',
		subtitle: '',
		img: '/repositories/lion.png',
		repo: 'https://github.com/code-front-braga/LION-KING-LANDING-PAGE',
		deploy: 'https://lion-king-landing-page.vercel.app/',
		tags: ['javascript', 'html', 'css', 'swiper'],
	},
];
